#!/usr/bin/env python3
"""Ruby SDK emitter.

Language-neutral spec parsing, grouping, aliasing, and the operations docs table
live in the vendored ``scripts/_sdkgen/core.py`` (synced from the API repo). This
file only maps OpenAPI types to Ruby/RBS types and writes the Ruby artifacts:
``lib/crawlora/operations.rb`` (runtime metadata + OperationId constants) and
``sig/crawlora.rbs`` (RBS signatures for the generated group methods).
"""
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _sdkgen import core  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPEC = ROOT / "openapi" / "public.json"
SPEC_PATH = Path(os.environ.get("CRAWLORA_OPENAPI_SPEC", DEFAULT_SPEC))

# Ruby reserved words; a generated method name that collides gets a trailing "_".
RUBY_KEYWORDS = frozenset(
    """
    BEGIN END alias and begin break case class def defined do else elsif end
    ensure false for if in module next nil not or redo rescue retry return self
    super then true undef unless until when while yield __FILE__ __LINE__
    __ENCODING__
    """.split()
)

POLICY = core.NamingPolicy(
    case_fn=lambda parts: "_".join(parts) or "call",
    dedup_sep="_",
    keywords=RUBY_KEYWORDS,
    tag_group_overrides={
        "AppStore": "app_store",
        "CoinGecko": "coin_gecko",
        "GooglePlay": "google_play",
        "ProductHunt": "product_hunt",
        "SimilarWeb": "similar_web",
        "SpotifyPodcasts": "spotify_podcasts",
        "TikTok": "tiktok",
        "YouTube": "youtube",
    },
)


def rb_literal(value, indent=0):
    """Serialize a JSON-ish Python value as a Ruby literal with string keys."""
    pad = "  " * indent
    inner = "  " * (indent + 1)
    if value is None:
        return "nil"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (list, tuple)):
        if not value:
            return "[]"
        items = [f"{inner}{rb_literal(item, indent + 1)}" for item in value]
        return "[\n" + ",\n".join(items) + f"\n{pad}]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = [f"{inner}{json.dumps(str(k))} => {rb_literal(v, indent + 1)}" for k, v in value.items()]
        return "{\n" + ",\n".join(items) + f"\n{pad}}}"
    raise TypeError(f"cannot serialize {type(value)!r} to a Ruby literal")


def rb_type(param):
    """Map an OpenAPI parameter to an RBS type."""
    enum_values = param.get("enum") or []
    if enum_values:
        return " | ".join(json.dumps(str(value)) for value in enum_values)
    typ = param.get("type")
    if typ == "integer":
        return "Integer"
    if typ == "number":
        return "Float"
    if typ == "boolean":
        return "bool"
    if typ == "array":
        return f"Array[{rb_type(param.get('items', {'type': 'string'}))}]"
    return "String"


def render_operations(model):
    const_lines = ["  module OperationId"]
    used = set()
    for operation_id, meta in sorted(model.meta.items(), key=lambda item: item[1]["type_base"]):
        const = "_".join(core.words(meta["type_base"])).upper() or "OPERATION"
        base = const
        i = 2
        while const in used:
            const = f"{base}_{i}"
            i += 1
        used.add(const)
        const_lines.append(f"    {const} = {json.dumps(operation_id)}")
    const_lines.append("  end")

    return (
        "# frozen_string_literal: true\n"
        "# Generated by scripts/generate.py. Do not edit manually.\n\n"
        "module Crawlora\n"
        f"  OPERATIONS = {rb_literal(model.operations, 1)}.freeze\n\n"
        f"  GROUPS = {rb_literal(model.groups, 1)}.freeze\n\n"
        f"  OPERATION_COUNT = {model.operation_count}\n\n"
        + "\n".join(const_lines)
        + "\nend\n"
    )


# Reserved per-call keyword options every grouped method accepts.
RESERVED_RBS_KW = [
    '?_response_type: ("auto" | "json" | "text" | "stream")',
    "?_timeout: Float",
    "?_headers: Hash[String, String]",
]
RBS_IDENT = re.compile(r"\A[a-z_][A-Za-z0-9_]*\Z")


def render_rbs(model):
    """Emit RBS signatures with each operation's typed keyword params, so Steep
    and Sorbet users get real per-method signatures instead of `**untyped`."""
    lines = [
        "# Generated by scripts/generate.py. Do not edit manually.",
        "module Crawlora",
        "  OPERATIONS: Hash[String, untyped]",
        "  GROUPS: Hash[String, Hash[String, String]]",
        "  OPERATION_COUNT: Integer",
        "",
    ]
    for group_name, methods in model.groups.items():
        klass = core.type_name(group_name, "group")
        lines.append(f"  class {klass}")
        lines.append("    def initialize: (Client, Hash[String, String]) -> void")
        for method_name, operation_id in methods.items():
            # All params are optional keywords (required-ness is validated at
            # runtime); names that aren't valid Ruby keyword identifiers fall
            # through to the `**untyped` rest.
            kw = [
                f"?{param['name']}: {rb_type(param)}"
                for param in model.meta[operation_id]["params"]
                if RBS_IDENT.match(param.get("name", ""))
            ]
            kw += RESERVED_RBS_KW
            lines.append(f"    def {method_name}: ({', '.join(kw)}, **untyped) -> untyped")
        lines.append("  end")
        lines.append("")
    lines.append("end")
    return "\n".join(lines) + "\n"


def main():
    if not SPEC_PATH.exists():
        raise SystemExit(f"public OpenAPI spec not found: {SPEC_PATH}")
    try:
        spec = json.loads(SPEC_PATH.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"failed to read OpenAPI spec {SPEC_PATH}: {exc}")
    (ROOT / "openapi").mkdir(exist_ok=True)
    target_spec = ROOT / "openapi" / "public.json"
    if SPEC_PATH.resolve() != target_spec.resolve():
        target_spec.write_text(SPEC_PATH.read_text())

    model = core.build_model(spec, POLICY)

    (ROOT / "lib" / "crawlora").mkdir(parents=True, exist_ok=True)
    (ROOT / "lib" / "crawlora" / "operations.rb").write_text(render_operations(model))
    (ROOT / "sig").mkdir(exist_ok=True)
    (ROOT / "sig" / "crawlora.rbs").write_text(render_rbs(model))
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "operations.md").write_text(
        core.operation_docs(model, title="Crawlora Ruby SDK Operations", type_render=rb_type)
    )


if __name__ == "__main__":
    main()
